// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoxTI.Challenge.CovidTracking.Infra.Migrations
{
    [DbContext(typeof(ContextBase))]
    partial class ContextBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entidades.CovidPais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Active_Cases_text")
                        .HasColumnType("int");

                    b.Property<string>("Country_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Last_Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("New_Cases_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("New_Deaths_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Total_Cases_text")
                        .HasColumnType("int");

                    b.Property<int?>("Total_Deaths_text")
                        .HasColumnType("int");

                    b.Property<int?>("Total_Recovered_text")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Country_text");

                    b.ToTable("Covid");
                });
#pragma warning restore 612, 618
        }
    }
}
